import { jsPDF } from "jspdf";
import { ExtractedEntity, EnrichmentData, RiskReport } from "../types";

// Corporate Colors
const COLORS = {
  PRIMARY: [9, 9, 11] as [number, number, number], // #09090b (Slate 950)
  SECONDARY: [2, 132, 199] as [number, number, number], // #0284c7 (Brand 600)
  ACCENT: [212, 175, 55] as [number, number, number], // #D4AF37 (Gold)
  TEXT: [51, 65, 85] as [number, number, number], // #334155 (Slate 700)
  LIGHT_BG: [248, 250, 252] as [number, number, number], // #f8fafc (Slate 50)
  BORDER: [226, 232, 240] as [number, number, number], // #e2e8f0 (Slate 200)
  DANGER: [220, 38, 38] as [number, number, number], // #dc2626 (Red 600)
  SUCCESS: [22, 163, 74] as [number, number, number] // #16a34a (Green 600)
};

export const generatePDFReport = (
  entity: ExtractedEntity,
  enrichment: EnrichmentData,
  report: RiskReport
) => {
  const doc = new jsPDF();
  let y = 25;
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - (margin * 2);

  // Helper: Draw Header on every page
  const drawHeader = () => {
    // Top Bar
    doc.setFillColor(...COLORS.PRIMARY);
    doc.rect(0, 0, pageWidth, 4, 'F');

    // FoundLab Logo Text
    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.setTextColor(...COLORS.PRIMARY);
    doc.text("FoundLab", margin, 18);
    
    // Subtitle
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.setCharSpace(2); // Tracking
    doc.text("INFRASTRUCTURE", margin, 23);
    doc.setCharSpace(0);

    // Confidential Stamp
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.DANGER);
    doc.setFont("helvetica", "bold");
    doc.text("CONFIDENTIAL // INTERNAL USE ONLY", pageWidth - margin, 18, { align: 'right' });
    
    // Date & Ref
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`${new Date().toLocaleDateString()} | REF: ${entity.idNumber || 'GEN-' + Math.random().toString(36).substr(2,6).toUpperCase()}`, pageWidth - margin, 23, { align: 'right' });

    // Divider Line
    doc.setDrawColor(...COLORS.BORDER);
    doc.setLineWidth(0.5);
    doc.line(margin, 28, pageWidth - margin, 28);
  };

  // Helper: Draw Footer on every page
  const drawFooter = (pageNumber: number) => {
    const footerY = pageHeight - 15;
    
    doc.setDrawColor(...COLORS.BORDER);
    doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
    
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by FoundLab Trust Engine v2.1", margin, footerY);
    doc.text(`Page ${pageNumber}`, pageWidth - margin, footerY, { align: 'right' });
    
    // Veritas Hash (Simulated)
    doc.setFont("courier", "normal");
    doc.setFontSize(6);
    doc.setTextColor(180);
    doc.text(`VERITAS_HASH: ${crypto.randomUUID()}`, margin, footerY + 4);
  };

  // Helper: Check Page Break
  const checkPageBreak = (heightNeeded: number) => {
    if (y + heightNeeded > pageHeight - 30) {
      doc.addPage();
      y = 35; // Reset Y below header
      drawHeader();
      drawFooter(doc.internal.getNumberOfPages());
    }
  };

  // --- INITIALIZE DOCUMENT ---
  drawHeader();
  drawFooter(1);
  y = 40;

  // --- 1. TITLE & EXECUTIVE SUMMARY ---
  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("Intelligence Dossier", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Subject: ${entity.name}`, margin, y);
  y += 15;

  // Executive Summary Box
  checkPageBreak(50);
  doc.setFillColor(...COLORS.LIGHT_BG);
  doc.setDrawColor(...COLORS.SECONDARY);
  doc.rect(margin, y, contentWidth, 40, 'FD');
  
  // Accent Bar on left
  doc.setFillColor(...COLORS.SECONDARY);
  doc.rect(margin, y, 2, 40, 'F');

  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("Executive Risk Summary", margin + 8, y + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.TEXT);
  const summaryLines = doc.splitTextToSize(report.summary, contentWidth - 16);
  doc.text(summaryLines, margin + 8, y + 20);
  y += 55;

  // --- 2. RISK SCORECARD ---
  checkPageBreak(60);
  
  // Container
  doc.setDrawColor(...COLORS.BORDER);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, y, contentWidth, 35, 2, 2, 'D');

  // Score
  const riskColor = report.riskLevel === 'HIGH' || report.riskLevel === 'CRITICAL' ? COLORS.DANGER : (report.riskLevel === 'MEDIUM' ? [234, 179, 8] as [number, number, number] : COLORS.SUCCESS);
  
  doc.setFont("times", "bold");
  doc.setFontSize(36);
  doc.setTextColor(...riskColor);
  doc.text(report.riskScore.toString(), margin + 10, y + 24);
  
  doc.setFontSize(12);
  doc.setTextColor(150);
  doc.text("/100", margin + 28, y + 24);

  // Level Label
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...riskColor);
  doc.text(report.riskLevel.toUpperCase(), margin + 50, y + 14);
  
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("AUTOMATED RISK ASSESSMENT", margin + 50, y + 22);

  // Recommendation (Right Side)
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text(`RECOMMENDATION: ${report.recommendation}`, pageWidth - margin - 10, y + 18, { align: 'right' });

  y += 50;

  // --- 3. ENTITY PROFILE GRID ---
  checkPageBreak(80);
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("01 // Target Designation", margin, y);
  
  doc.setDrawColor(...COLORS.BORDER);
  doc.line(margin, y + 3, pageWidth - margin, y + 3);
  y += 15;

  const rowHeight = 10;
  const col1X = margin;
  const col2X = margin + (contentWidth / 2);

  // Function to draw key-value pair
  const drawField = (label: string, value: string, x: number, currentY: number) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(label.toUpperCase(), x, currentY);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.PRIMARY);
      doc.text(value || "N/A", x, currentY + 5);
  };

  drawField("Entity Name", entity.name, col1X, y);
  drawField("Entity Type", entity.type, col2X, y);
  y += 15;
  drawField("Identification", entity.idNumber || "N/A", col1X, y);
  drawField("Nationality", entity.nationality || "N/A", col2X, y);
  y += 15;
  drawField("Date of Birth / Incorp", entity.dateOfBirth || "N/A", col1X, y);
  drawField("Registered Address", entity.address || "N/A", col2X, y);
  y += 25;

  // --- 4. DEEP DIVE ANALYSIS ---
  checkPageBreak(80);
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("02 // Deep Dive Analysis", margin, y);
  doc.line(margin, y + 3, pageWidth - margin, y + 3);
  y += 15;

  // FATF & OFAC Boxes
  const boxWidth = (contentWidth - 10) / 2;
  
  // Calculate heights
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const fatfLines = doc.splitTextToSize(report.fatfAlignment, boxWidth - 10);
  const ofacLines = doc.splitTextToSize(report.ofacScreening, boxWidth - 10);
  
  const fatfHeight = (fatfLines.length * 4) + 20;
  const ofacHeight = (ofacLines.length * 4) + 20;
  const boxHeight = Math.max(fatfHeight, ofacHeight, 40); // Min 40

  checkPageBreak(boxHeight + 10);

  // FATF
  doc.setFillColor(...COLORS.LIGHT_BG);
  doc.rect(margin, y, boxWidth, boxHeight, 'F');
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("FATF Alignment", margin + 5, y + 8);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.TEXT);
  doc.text(fatfLines, margin + 5, y + 16);

  // OFAC
  doc.setFillColor(...COLORS.LIGHT_BG); // Explicitly reset fill color
  doc.rect(margin + boxWidth + 10, y, boxWidth, boxHeight, 'F');
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("OFAC Screening", margin + boxWidth + 15, y + 8);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.TEXT);
  doc.text(ofacLines, margin + boxWidth + 15, y + 16);

  y += boxHeight + 10;

  // RED FLAGS
  if (report.redFlags.length > 0) {
      checkPageBreak(40);
      doc.setFillColor(254, 242, 242); // Red 50
      doc.setDrawColor(252, 165, 165); // Red 300
      doc.rect(margin, y, contentWidth, 10 + (report.redFlags.length * 8), 'DF');
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.DANGER);
      doc.text("DETECTED RISK INDICATORS", margin + 5, y + 8);
      
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.DANGER);
      let flagY = y + 16;
      report.redFlags.forEach(flag => {
          doc.text(`• ${flag}`, margin + 5, flagY);
          flagY += 6;
      });
      y = flagY + 10;
  }

  // --- 5. ENRICHMENT DATA ---
  checkPageBreak(60);
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("03 // Intelligence Enrichment", margin, y);
  doc.setDrawColor(...COLORS.BORDER);
  doc.line(margin, y + 3, pageWidth - margin, y + 3);
  y += 15;

  // Location
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Geospatial Verification", margin, y);
  doc.setFont("helvetica", "normal");
  const locStatus = enrichment.locationVerification.verified ? "CONFIRMED" : "UNVERIFIED";
  doc.setTextColor(enrichment.locationVerification.verified ? COLORS.SUCCESS[0] : 200, enrichment.locationVerification.verified ? COLORS.SUCCESS[1] : 100, 0);
  doc.text(`[ ${locStatus} ]`, margin + 50, y);
  
  y += 6;
  doc.setTextColor(...COLORS.TEXT);
  doc.setFontSize(9);
  const locDetails = doc.splitTextToSize(enrichment.locationVerification.details, contentWidth);
  doc.text(locDetails, margin, y);
  y += (locDetails.length * 5) + 10;

  // Adverse Media
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text(`Adverse Media Hits (${enrichment.adverseMedia.length})`, margin, y);
  y += 8;

  if (enrichment.adverseMedia.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setTextColor(150);
      doc.text("No significant adverse media found in screened databases.", margin, y);
  } else {
      enrichment.adverseMedia.forEach(media => {
          checkPageBreak(25);
          doc.setFont("helvetica", "bold");
          doc.setFontSize(9);
          doc.setTextColor(...COLORS.PRIMARY);
          doc.text(`• ${media.title}`, margin, y);
          y += 5;
          
          doc.setFont("helvetica", "normal");
          doc.setFontSize(8);
          doc.setTextColor(...COLORS.TEXT);
          const snippet = doc.splitTextToSize(media.snippet, contentWidth - 5);
          doc.text(snippet, margin + 5, y);
          y += (snippet.length * 4) + 2;
          
          doc.setTextColor(...COLORS.SECONDARY);
          doc.textWithLink("Source Link >>", margin + 5, y, { url: media.url });
          y += 8;
      });
  }

  doc.save(`FoundLab_Dossier_${entity.name.replace(/\s/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const generateDeepSearchPDF = (
  topic: string,
  reportText: string,
  sources: { title: string; uri: string; trustScore?: number }[]
) => {
  const doc = new jsPDF();
  let y = 25;
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - (margin * 2);

  const drawHeader = () => {
    doc.setFillColor(...COLORS.PRIMARY);
    doc.rect(0, 0, pageWidth, 4, 'F');
    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.setTextColor(...COLORS.PRIMARY);
    doc.text("FoundLab", margin, 18);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.setCharSpace(2);
    doc.text("DEEPSEARCH", margin, 23);
    doc.setCharSpace(0);
    doc.line(margin, 28, pageWidth - margin, 28);
  };

  const drawFooter = (pageNum: number) => {
      const footerY = pageHeight - 15;
      doc.setDrawColor(...COLORS.BORDER);
      doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("FoundLab Autonomous Agent v2.1", margin, footerY);
      doc.text(`Page ${pageNum}`, pageWidth - margin, footerY, { align: 'right' });
  };

  const checkPageBreak = (heightNeeded: number) => {
    if (y + heightNeeded > pageHeight - 30) {
      doc.addPage();
      y = 35;
      drawHeader();
      drawFooter(doc.internal.getNumberOfPages());
    }
  };

  drawHeader();
  drawFooter(1);
  y = 40;

  // Title
  doc.setFont("times", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text(`Research Topic: ${topic}`, margin, y);
  y += 15;

  // Body
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.TEXT);
  
  const lines = doc.splitTextToSize(reportText, contentWidth);
  lines.forEach((line: string) => {
      checkPageBreak(5);
      doc.text(line, margin, y);
      y += 5;
  });

  // Sources
  y += 15;
  checkPageBreak(40);
  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.PRIMARY);
  doc.text("Cited Intelligence Sources", margin, y);
  doc.line(margin, y+2, pageWidth-margin, y+2);
  y += 10;

  sources.forEach(source => {
      checkPageBreak(15);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.SECONDARY);
      doc.textWithLink(`[${source.trustScore || '?'}] ${source.title.substring(0, 60)}`, margin, y, { url: source.uri });
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(source.uri.substring(0, 80) + "...", margin, y);
      y += 8;
  });

  doc.save(`FoundLab_Research_${topic.substring(0, 10).replace(/\s/g, '_')}.pdf`);
};